#  Copyright (c) 2012-2023, Puzzle ITC GmbH. This file is part of
#  hitobito_generic and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_generic.

application:
  # The languages available in the menu
  languages:
    de: Deutsch
    en: English
    fr: Fran√ßais
  footer:
    links:
      "Dokumentation": https://hitobito.readthedocs.io
      "E-Mail an Support": 'mailto:it@alumni-ed.ch'

root_email: <%= 'it@alumni-ed.ch' %>
mail_domain: alumni-ed.ch

application:
  name: alumni-ed  # set same name in email.sender and email.mass_recipient

email:
  # Sender for all emails sent by the application.
  # Overwrite in different languages using the settings.email.sender translation key.
  sender: <%= "alumni-ed <noreply@alumni-ed.ch>" %>

  # If mass emails are sent, this recipient is used in the to field,
  # while the actual recipients go in the bcc field.
  mass_recipient: <%= "alumni-ed <noreply@alumni-ed.ch>" %>
